-- M4.5 conversational Automation delivery.
--
-- One shared Cron tick creates durable occurrences, workers claim them with
-- short leases, and completion atomically appends the verified assistant
-- message before a separate, retryable push-delivery record is created.

alter table public.automation_runs
  add column conversation_id uuid
    references public.conversations(id) on delete set null,
  add column conversation_message_id uuid unique
    references public.messages(id) on delete set null;

create index automation_runs_conversation_idx
  on public.automation_runs (conversation_id, created_at desc)
  where conversation_id is not null;

create table public.automation_run_deliveries (
  id uuid primary key default gen_random_uuid(),
  automation_run_id uuid not null unique
    references public.automation_runs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  conversation_id uuid not null
    references public.conversations(id) on delete cascade,
  message_id uuid not null unique
    references public.messages(id) on delete cascade,
  title text not null,
  preview text not null,
  status text not null default 'pending',
  attempt_count smallint not null default 0,
  available_at timestamptz not null default now(),
  lease_expires_at timestamptz,
  provider_summary jsonb not null default '{}'::jsonb,
  sent_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint automation_run_deliveries_title_length
    check (char_length(btrim(title)) between 1 and 200),
  constraint automation_run_deliveries_preview_length
    check (char_length(btrim(preview)) between 1 and 500),
  constraint automation_run_deliveries_status_check
    check (status in (
      'pending', 'processing', 'retrying',
      'sent', 'partial', 'no_devices', 'failed'
    )),
  constraint automation_run_deliveries_attempt_count_check
    check (attempt_count between 0 and 10),
  constraint automation_run_deliveries_summary_object
    check (jsonb_typeof(provider_summary) = 'object'),
  constraint automation_run_deliveries_completion_state
    check (
      (status in ('sent', 'partial', 'no_devices', 'failed'))
      = (completed_at is not null)
    ),
  constraint automation_run_deliveries_updated_order
    check (updated_at >= created_at)
);

alter table public.automation_run_deliveries enable row level security;
revoke all on public.automation_run_deliveries
  from public, anon, authenticated;
grant all on public.automation_run_deliveries to service_role;

create index automation_run_deliveries_ready_idx
  on public.automation_run_deliveries (available_at, created_at, id)
  where status in ('pending', 'retrying');
create index automation_run_deliveries_stale_lease_idx
  on public.automation_run_deliveries (lease_expires_at, id)
  where status = 'processing';
create index automation_run_deliveries_user_idx
  on public.automation_run_deliveries (user_id, created_at desc);
create index automation_run_deliveries_conversation_idx
  on public.automation_run_deliveries (conversation_id, created_at desc);

create trigger set_automation_run_delivery_updated_at
before update on public.automation_run_deliveries
for each row execute function public.update_updated_at_column();

create table public.automation_delivery_attempts (
  id bigint generated by default as identity primary key,
  delivery_id uuid not null
    references public.automation_run_deliveries(id) on delete cascade,
  push_device_id bigint not null
    references public.push_devices(id) on delete cascade,
  attempt_number smallint not null,
  status text not null,
  provider_message_id text,
  error_code text,
  error_message text,
  created_at timestamptz not null default now(),
  constraint automation_delivery_attempts_unique
    unique (delivery_id, push_device_id, attempt_number),
  constraint automation_delivery_attempts_number_check
    check (attempt_number between 1 and 10),
  constraint automation_delivery_attempts_status_check
    check (status in ('sent', 'transient_failure', 'permanent_failure')),
  constraint automation_delivery_attempts_message_id_length
    check (provider_message_id is null or char_length(provider_message_id) <= 500),
  constraint automation_delivery_attempts_error_code_length
    check (error_code is null or char_length(error_code) <= 100),
  constraint automation_delivery_attempts_error_message_length
    check (error_message is null or char_length(error_message) <= 500)
);

alter table public.automation_delivery_attempts enable row level security;
revoke all on public.automation_delivery_attempts
  from public, anon, authenticated;
grant all on public.automation_delivery_attempts to service_role;

create index automation_delivery_attempts_device_idx
  on public.automation_delivery_attempts (push_device_id, created_at desc);
create index automation_delivery_attempts_sent_idx
  on public.automation_delivery_attempts (delivery_id, push_device_id)
  where status = 'sent';

create function public.claim_due_automation_runs(
  p_limit integer default 4
)
returns table (
  run_id uuid,
  automation_id uuid,
  user_id uuid,
  conversation_id uuid,
  automation_version integer,
  scheduled_for timestamptz,
  attempt_number smallint,
  template_snapshot jsonb
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_mode text;
  v_market_enabled boolean;
begin
  if (select auth.jwt() ->> 'role') is distinct from 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  if p_limit < 1 or p_limit > 10 then
    raise exception 'p_limit must be between 1 and 10'
      using errcode = '22023';
  end if;

  select case
    when count(*) = 3
      and bool_and(enabled)
      and bool_and(payload ->> 'mode' in ('internal', 'full'))
    then case
      when bool_and(payload ->> 'mode' = 'full') then 'full'
      else 'internal'
    end
    else null
  end
  into v_mode
  from public.feature_flags
  where key in (
    'automations',
    'automation_web_retrieval',
    'automation_validation'
  );

  if v_mode is null then
    return;
  end if;

  select coalesce(enabled, false)
    and payload ->> 'mode' in ('internal', 'full')
  into v_market_enabled
  from public.feature_flags
  where key = 'automation_market_data';

  v_market_enabled := coalesce(v_market_enabled, false);

  with due as materialized (
    select a.*
    from public.automations a
    where a.status = 'active'
      and a.next_run_at <= pg_catalog.now()
      and (a.kind <> 'market_briefing' or v_market_enabled)
      and exists (
        select 1
        from public.app_entitlements e
        where e.user_id = a.user_id
          and e.tier = 'paid'
          and (e.expires_at is null or e.expires_at > pg_catalog.now())
          and (v_mode = 'full' or e.model_policy_canary = true)
      )
      and not exists (
        select 1
        from public.automation_runs existing
        where existing.automation_id = a.id
          and existing.scheduled_for = a.next_run_at
      )
    order by a.next_run_at, a.id
    limit p_limit
    for update of a skip locked
  )
  insert into public.automation_runs (
    automation_id,
    user_id,
    conversation_id,
    automation_version,
    scheduled_for,
    trigger_type,
    template_snapshot
  )
  select
    due.id,
    due.user_id,
    due.conversation_id,
    due.version,
    due.next_run_at,
    'scheduled',
    jsonb_build_object(
      'automation_id', due.id,
      'kind', due.kind,
      'title', due.title,
      'timezone', due.timezone,
      'start_local', due.start_local,
      'schedule_rule', due.schedule_rule,
      'config', due.config,
      'source_policy', due.source_policy,
      'delivery_preferences', due.delivery_preferences
    )
  from due
  on conflict on constraint automation_runs_occurrence_unique do nothing;

  return query
  with candidates as materialized (
    select r.id
    from public.automation_runs r
    where (
      (r.status = 'queued' and r.available_at <= pg_catalog.now())
      or (
        r.status in ('running', 'verifying')
        and r.lease_expires_at <= pg_catalog.now()
      )
    )
      and r.attempt_count < 10
    order by r.available_at, r.created_at, r.id
    limit p_limit
    for update of r skip locked
  ), claimed as (
    update public.automation_runs r
    set
      status = 'running',
      attempt_count = r.attempt_count + 1,
      lease_expires_at = pg_catalog.now() + interval '5 minutes',
      started_at = coalesce(r.started_at, pg_catalog.now()),
      updated_at = pg_catalog.now()
    from candidates c
    where r.id = c.id
    returning r.*
  )
  select
    claimed.id,
    claimed.automation_id,
    claimed.user_id,
    claimed.conversation_id,
    claimed.automation_version,
    claimed.scheduled_for,
    claimed.attempt_count,
    claimed.template_snapshot
  from claimed
  order by claimed.scheduled_for, claimed.id;
end;
$$;

comment on function public.claim_due_automation_runs(integer) is
  'Creates unique due occurrences and leases a small batch without holding locks during model or network calls.';

revoke all on function public.claim_due_automation_runs(integer)
  from public, anon, authenticated;
grant execute on function public.claim_due_automation_runs(integer)
  to service_role;

create function public.retry_automation_run(
  p_run_id uuid,
  p_delay_seconds integer,
  p_error_code text,
  p_error_message text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.jwt() ->> 'role') is distinct from 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  if p_delay_seconds < 5 or p_delay_seconds > 3600
    or p_error_code is null or char_length(p_error_code) > 100
    or p_error_message is null or char_length(p_error_message) > 500 then
    raise exception 'invalid retry values' using errcode = '22023';
  end if;

  update public.automation_runs
  set
    status = 'queued',
    available_at = pg_catalog.now()
      + pg_catalog.make_interval(secs => p_delay_seconds),
    lease_expires_at = null,
    error_code = p_error_code,
    error_message = p_error_message,
    updated_at = pg_catalog.now()
  where id = p_run_id
    and status in ('running', 'verifying');

  return found;
end;
$$;

revoke all on function public.retry_automation_run(uuid,integer,text,text)
  from public, anon, authenticated;
grant execute on function public.retry_automation_run(uuid,integer,text,text)
  to service_role;

create function public.finish_automation_run(
  p_run_id uuid,
  p_status text,
  p_message_content text,
  p_report jsonb,
  p_preview text,
  p_claims jsonb,
  p_sources jsonb,
  p_verification jsonb,
  p_generation_response_id text,
  p_verification_response_id text,
  p_generation_usage_ledger_id uuid,
  p_verification_usage_ledger_id uuid,
  p_next_run_at timestamptz,
  p_create_delivery boolean,
  p_error_code text default null,
  p_error_message text default null
)
returns table (
  conversation_id uuid,
  message_id uuid,
  delivery_id uuid
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_run public.automation_runs%rowtype;
  v_automation public.automations%rowtype;
  v_conversation_id uuid;
  v_message_id uuid;
  v_delivery_id uuid;
begin
  if (select auth.jwt() ->> 'role') is distinct from 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  if p_status not in ('succeeded', 'withheld', 'failed')
    or p_report is null or jsonb_typeof(p_report) <> 'object'
    or p_claims is null or jsonb_typeof(p_claims) <> 'array'
    or p_sources is null or jsonb_typeof(p_sources) <> 'array'
    or p_verification is null or jsonb_typeof(p_verification) <> 'object'
    or (p_preview is not null and char_length(p_preview) > 500)
    or (p_error_code is not null and char_length(p_error_code) > 100)
    or (p_error_message is not null and char_length(p_error_message) > 500)
    or (
      p_status in ('succeeded', 'withheld')
      and (p_message_content is null or char_length(btrim(p_message_content)) = 0)
    )
    or (
      p_create_delivery
      and (
        p_status not in ('succeeded', 'withheld')
        or p_preview is null
        or char_length(btrim(p_preview)) = 0
      )
    ) then
    raise exception 'invalid Automation completion values'
      using errcode = '22023';
  end if;

  select *
  into v_run
  from public.automation_runs
  where id = p_run_id
  for update;

  if not found then
    return;
  end if;
  if v_run.status in ('succeeded', 'withheld', 'failed', 'cancelled') then
    select d.id into v_delivery_id
    from public.automation_run_deliveries d
    where d.automation_run_id = v_run.id;
    return query select
      v_run.conversation_id,
      v_run.conversation_message_id,
      v_delivery_id;
    return;
  end if;
  if v_run.status not in ('running', 'verifying') then
    return;
  end if;

  select *
  into v_automation
  from public.automations
  where id = v_run.automation_id
    and user_id = v_run.user_id
  for update;

  if not found then
    raise exception 'Automation no longer exists' using errcode = '55000';
  end if;

  v_conversation_id := coalesce(v_run.conversation_id, v_automation.conversation_id);
  if p_status in ('succeeded', 'withheld') and v_conversation_id is null then
    insert into public.conversations (
      user_id,
      title,
      created_at,
      updated_at,
      is_pinned
    ) values (
      v_run.user_id,
      'Automation: ' || v_automation.title,
      pg_catalog.now(),
      pg_catalog.now(),
      false
    )
    returning id into v_conversation_id;

    update public.automations
    set conversation_id = v_conversation_id,
        updated_at = pg_catalog.now()
    where id = v_automation.id;
  end if;

  if p_status in ('succeeded', 'withheld') then
    insert into public.messages (
      conversation_id,
      content,
      is_ai,
      created_at
    ) values (
      v_conversation_id,
      p_message_content,
      true,
      pg_catalog.now()
    )
    returning id into v_message_id;

    update public.conversations
    set updated_at = pg_catalog.now(),
        archived_at = null
    where id = v_conversation_id
      and user_id = v_run.user_id;
  end if;

  update public.automation_runs
  set
    conversation_id = v_conversation_id,
    conversation_message_id = v_message_id,
    status = p_status,
    report = p_report,
    preview = p_preview,
    claims = p_claims,
    sources = p_sources,
    verification = p_verification,
    generation_response_id = p_generation_response_id,
    verification_response_id = p_verification_response_id,
    generation_usage_ledger_id = p_generation_usage_ledger_id,
    verification_usage_ledger_id = p_verification_usage_ledger_id,
    error_code = p_error_code,
    error_message = p_error_message,
    completed_at = pg_catalog.now(),
    lease_expires_at = null,
    updated_at = pg_catalog.now()
  where id = v_run.id;

  if v_automation.status = 'active'
    and v_automation.next_run_at = v_run.scheduled_for then
    update public.automations
    set
      status = case when p_next_run_at is null then 'paused' else status end,
      next_run_at = coalesce(p_next_run_at, next_run_at),
      last_run_at = v_run.scheduled_for,
      version = version + 1,
      updated_at = pg_catalog.now()
    where id = v_automation.id;
  end if;

  if p_create_delivery and v_message_id is not null then
    insert into public.automation_run_deliveries (
      automation_run_id,
      user_id,
      conversation_id,
      message_id,
      title,
      preview
    ) values (
      v_run.id,
      v_run.user_id,
      v_conversation_id,
      v_message_id,
      v_automation.title,
      p_preview
    )
    on conflict (automation_run_id) do update
    set updated_at = pg_catalog.now()
    returning id into v_delivery_id;
  end if;

  return query select v_conversation_id, v_message_id, v_delivery_id;
end;
$$;

revoke all on function public.finish_automation_run(
  uuid,text,text,jsonb,text,jsonb,jsonb,jsonb,text,text,uuid,uuid,
  timestamptz,boolean,text,text
) from public, anon, authenticated;
grant execute on function public.finish_automation_run(
  uuid,text,text,jsonb,text,jsonb,jsonb,jsonb,text,text,uuid,uuid,
  timestamptz,boolean,text,text
) to service_role;

create function public.claim_due_automation_deliveries(
  p_limit integer default 10
)
returns table (
  delivery_id uuid,
  automation_run_id uuid,
  user_id uuid,
  conversation_id uuid,
  message_id uuid,
  title text,
  preview text,
  attempt_number smallint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_enabled boolean;
  v_mode text;
begin
  if (select auth.jwt() ->> 'role') is distinct from 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  if p_limit < 1 or p_limit > 50 then
    raise exception 'p_limit must be between 1 and 50'
      using errcode = '22023';
  end if;

  select enabled, payload ->> 'mode'
  into v_enabled, v_mode
  from public.feature_flags
  where key = 'automation_notifications';

  if not coalesce(v_enabled, false)
    or v_mode not in ('internal', 'full') then
    return;
  end if;

  return query
  with candidates as materialized (
    select d.id
    from public.automation_run_deliveries d
    where (
      (d.status in ('pending', 'retrying') and d.available_at <= pg_catalog.now())
      or (d.status = 'processing' and d.lease_expires_at <= pg_catalog.now())
    )
      and d.attempt_count < 10
      and (
        v_mode = 'full'
        or exists (
          select 1
          from public.app_entitlements e
          where e.user_id = d.user_id
            and e.model_policy_canary = true
        )
      )
    order by d.available_at, d.created_at, d.id
    limit p_limit
    for update of d skip locked
  ), claimed as (
    update public.automation_run_deliveries d
    set
      status = 'processing',
      attempt_count = d.attempt_count + 1,
      lease_expires_at = pg_catalog.now() + interval '2 minutes',
      updated_at = pg_catalog.now()
    from candidates c
    where d.id = c.id
    returning d.*
  )
  select
    claimed.id,
    claimed.automation_run_id,
    claimed.user_id,
    claimed.conversation_id,
    claimed.message_id,
    claimed.title,
    claimed.preview,
    claimed.attempt_count
  from claimed
  order by claimed.created_at, claimed.id;
end;
$$;

revoke all on function public.claim_due_automation_deliveries(integer)
  from public, anon, authenticated;
grant execute on function public.claim_due_automation_deliveries(integer)
  to service_role;

create function public.retry_automation_delivery(
  p_delivery_id uuid,
  p_delay_seconds integer,
  p_summary jsonb
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.jwt() ->> 'role') is distinct from 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  if p_delay_seconds < 5 or p_delay_seconds > 3600
    or p_summary is null or jsonb_typeof(p_summary) <> 'object' then
    raise exception 'invalid retry values' using errcode = '22023';
  end if;

  update public.automation_run_deliveries
  set
    status = 'retrying',
    available_at = pg_catalog.now()
      + pg_catalog.make_interval(secs => p_delay_seconds),
    lease_expires_at = null,
    provider_summary = p_summary,
    updated_at = pg_catalog.now()
  where id = p_delivery_id
    and status = 'processing';

  return found;
end;
$$;

revoke all on function public.retry_automation_delivery(uuid,integer,jsonb)
  from public, anon, authenticated;
grant execute on function public.retry_automation_delivery(uuid,integer,jsonb)
  to service_role;

create function public.finish_automation_delivery(
  p_delivery_id uuid,
  p_outcome text,
  p_summary jsonb
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.jwt() ->> 'role') is distinct from 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  if p_outcome not in ('sent', 'partial', 'no_devices', 'failed')
    or p_summary is null or jsonb_typeof(p_summary) <> 'object' then
    raise exception 'invalid completion values' using errcode = '22023';
  end if;

  update public.automation_run_deliveries
  set
    status = p_outcome,
    provider_summary = p_summary,
    sent_at = case
      when p_outcome in ('sent', 'partial') then pg_catalog.now()
      else null
    end,
    completed_at = pg_catalog.now(),
    lease_expires_at = null,
    updated_at = pg_catalog.now()
  where id = p_delivery_id
    and status = 'processing';

  if found then return true; end if;

  return exists (
    select 1
    from public.automation_run_deliveries
    where id = p_delivery_id
      and status in ('sent', 'partial', 'no_devices', 'failed')
  );
end;
$$;

revoke all on function public.finish_automation_delivery(uuid,text,jsonb)
  from public, anon, authenticated;
grant execute on function public.finish_automation_delivery(uuid,text,jsonb)
  to service_role;

-- Reuse the existing scheduler secret. It authenticates only internal Cron
-- dispatchers and remains in Vault/Edge Function secrets, never in git.
select cron.schedule(
  'howai-dispatch-automations',
  '* * * * *',
  $schedule$
    select net.http_post(
      url := secrets.project_url || '/functions/v1/dispatch-automations',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-howai-cron-secret', secrets.dispatch_secret
      ),
      body := '{}'::jsonb,
      timeout_milliseconds := 150000
    )
    from (
      select
        max(decrypted_secret) filter (
          where name = 'howai_project_url'
        ) as project_url,
        max(decrypted_secret) filter (
          where name = 'howai_reminder_dispatch_secret'
        ) as dispatch_secret
      from vault.decrypted_secrets
    ) secrets
    where secrets.project_url is not null
      and secrets.dispatch_secret is not null;
  $schedule$
);
